# Generated by Django 5.0.2 on 2024-02-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=50)),
            ],
        ),
    ]
